### Criar novo usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "Maria",
  "email": "maria@email.com",
  "password": "11111"
}


### Listar todos os usuários
GET http://localhost:3000/api/users


### Atualizar usuário
PUT http://localhost:3000/api/users/<ID_DO_USUARIO>
Content-Type: application/json

{
  "email": "novoemail@email.com"
}


### Deletar usuário
DELETE http://localhost:3000/api/users/<ID_DO_USUARIO>


### NoSQL Injection - Tentativa de login sem saber a senha
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "username": { "$ne": null },
  "password": { "$ne": null }
}

### XSS - Criar usuário com script malicioso
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "<script>alert('XSS')</script>",
  "email": "xss@teste.com",
  "password": "123456"
}

